// ============================================================
// CoreMaX AI — 256+ CURRENCIES DATABASE
// ISO 4217 Fiat, Metals/IMF, 60+ Crypto, Regional & Obsolete
// ============================================================

export const ALL_CURRENCIES = [
  // --- TOP POPULAR & CIS (15) ---
  { code:'RUB', sym:'₽', name:'Российский рубль', flag:'🇷🇺', rate:1, region:'europe', popular:true },
  { code:'USD', sym:'$', name:'Доллар США', flag:'🇺🇸', rate:0.0108, region:'america', popular:true },
  { code:'EUR', sym:'€', name:'Евро', flag:'🇪🇺', rate:0.0098, region:'europe', popular:true },
  { code:'TJS', sym:'TJS', name:'Таджикский сомони', flag:'🇹🇯', rate:0.118, region:'asia', popular:true },
  { code:'KZT', sym:'₸', name:'Казахстанский тенге', flag:'🇰🇿', rate:5.2, region:'asia', popular:true },
  { code:'UZS', sym:'so\'m', name:'Узбекский сум', flag:'🇺🇿', rate:138.5, region:'asia', popular:true },
  { code:'KGS', sym:'сом', name:'Кыргызский сом', flag:'🇰🇬', rate:0.96, region:'asia', popular:true },
  { code:'BYN', sym:'Br', name:'Белорусский рубль', flag:'🇧🇾', rate:0.035, region:'europe', popular:true },
  { code:'UAH', sym:'₴', name:'Украинская гривна', flag:'🇺🇦', rate:0.44, region:'europe', popular:true },
  { code:'AZN', sym:'₼', name:'Азербайджанский манат', flag:'🇦🇿', rate:0.0184, region:'asia', popular:true },
  { code:'AMD', sym:'֏', name:'Армянский драм', flag:'🇦🇲', rate:4.25, region:'asia', popular:true },
  { code:'GEL', sym:'₾', name:'Грузинский лари', flag:'🇬🇪', rate:0.029, region:'asia', popular:true },
  { code:'AED', sym:'AED', name:'Дирхам ОАЭ', flag:'🇦🇪', rate:0.0397, region:'asia', popular:true },
  { code:'TRY', sym:'₺', name:'Турецкая лира', flag:'🇹🇷', rate:0.37, region:'asia', popular:true },
  { code:'CNY', sym:'¥', name:'Китайский юань', flag:'🇨🇳', rate:0.078, region:'asia', popular:true },

  // --- ASIA & MIDDLE EAST (38) ---
  { code:'GBP', sym:'£', name:'Фунт стерлингов', flag:'🇬🇧', rate:0.0084, region:'europe' },
  { code:'CHF', sym:'CHF', name:'Швейцарский франк', flag:'🇨🇭', rate:0.0095, region:'europe' },
  { code:'JPY', sym:'¥', name:'Японская иена', flag:'🇯🇵', rate:1.64, region:'asia' },
  { code:'INR', sym:'₹', name:'Индийская рупия', flag:'🇮🇳', rate:0.91, region:'asia' },
  { code:'KRW', sym:'₩', name:'Южнокорейская вона', flag:'🇰🇷', rate:14.8, region:'asia' },
  { code:'SGD', sym:'S$', name:'Сингапурский доллар', flag:'🇸🇬', rate:0.0143, region:'asia' },
  { code:'THB', sym:'฿', name:'Тайский бат', flag:'🇹🇭', rate:0.38, region:'asia' },
  { code:'SAR', sym:'SR', name:'Саудовский риал', flag:'🇸🇦', rate:0.0405, region:'asia' },
  { code:'QAR', sym:'QR', name:'Катарский риал', flag:'🇶🇦', rate:0.0393, region:'asia' },
  { code:'ILS', sym:'₪', name:'Израильский шекель', flag:'🇮🇱', rate:0.040, region:'asia' },
  { code:'IDR', sym:'Rp', name:'Индонезийская рупия', flag:'🇮🇩', rate:172.0, region:'asia' },
  { code:'MYR', sym:'RM', name:'Малайзийский ринггит', flag:'🇲🇾', rate:0.048, region:'asia' },
  { code:'PHP', sym:'₱', name:'Филиппинское песо', flag:'🇵🇭', rate:0.62, region:'asia' },
  { code:'VND', sym:'₫', name:'Вьетнамский донг', flag:'🇻🇳', rate:272.0, region:'asia' },
  { code:'PKR', sym:'₨', name:'Пакистанская рупия', flag:'🇵🇰', rate:3.02, region:'asia' },
  { code:'BDT', sym:'৳', name:'Бангладешская така', flag:'🇧🇩', rate:1.32, region:'asia' },
  { code:'LKR', sym:'Rs', name:'Ланкийская рупия', flag:'🇱🇰', rate:3.25, region:'asia' },
  { code:'KWD', sym:'KD', name:'Кувейтский динар', flag:'🇰🇼', rate:0.0033, region:'asia' },
  { code:'BHD', sym:'BD', name:'Бахрейнский динар', flag:'🇧🇭', rate:0.0041, region:'asia' },
  { code:'OMR', sym:'OR', name:'Оманский риал', flag:'🇴🇲', rate:0.00415, region:'asia' },
  { code:'JOD', sym:'JD', name:'Иорданский динар', flag:'🇯🇴', rate:0.0076, region:'asia' },
  { code:'LAK', sym:'₭', name:'Лаосский кип', flag:'🇱🇦', rate:235.0, region:'asia' },
  { code:'LBP', sym:'ل.ل', name:'Ливанский фунт', flag:'🇱🇧', rate:970.0, region:'asia' },
  { code:'MOP', sym:'MOP$', name:'Патака Макао', flag:'🇲🇴', rate:0.086, region:'asia' },
  { code:'MVR', sym:'Rf', name:'Мальдивская руфия', flag:'🇲🇻', rate:0.166, region:'asia' },
  { code:'MMK', sym:'K', name:'Мьянманский кьят', flag:'🇲🇲', rate:22.5, region:'asia' },
  { code:'NPR', sym:'Rs', name:'Непальская рупия', flag:'🇳🇵', rate:1.45, region:'asia' },
  { code:'TMT', sym:'m', name:'Туркменский манат', flag:'🇹🇲', rate:0.038, region:'asia' },
  { code:'AFN', sym:'؋', name:'Афганский афгани', flag:'🇦🇫', rate:0.75, region:'asia' },
  { code:'IQD', sym:'ID', name:'Иракский динар', flag:'🇮🇶', rate:14.1, region:'asia' },
  { code:'IRR', sym:'﷼', name:'Иранский риал', flag:'🇮🇷', rate:450.0, region:'asia' },
  { code:'SYP', sym:'LS', name:'Сирийский фунт', flag:'🇸🇾', rate:140.0, region:'asia' },
  { code:'YER', sym:'﷼', name:'Йеменский риал', flag:'🇾🇪', rate:2.7, region:'asia' },
  { code:'KHR', sym:'៛', name:'Камбоджийский риель', flag:'🇰🇭', rate:44.0, region:'asia' },
  { code:'BND', sym:'B$', name:'Брунейский доллар', flag:'🇧🇳', rate:0.0143, region:'asia' },
  { code:'BTN', sym:'Nu.', name:'Бутанский нгултрум', flag:'🇧🇹', rate:0.91, region:'asia' },
  { code:'MNT', sym:'₮', name:'Монгольский тугрик', flag:'🇲🇳', rate:36.5, region:'asia' },
  { code:'KPW', sym:'₩', name:'Северокорейская вона', flag:'🇰🇵', rate:9.7, region:'asia' },
  { code:'CNH', sym:'¥', name:'Офшорный юань', flag:'🇨🇳', rate:0.078, region:'asia' },

  // --- EUROPE (30) ---
  { code:'PLN', sym:'zł', name:'Польский злотый', flag:'🇵🇱', rate:0.043, region:'europe' },
  { code:'CZK', sym:'Kč', name:'Чешская крона', flag:'🇨🇿', rate:0.25, region:'europe' },
  { code:'HUF', sym:'Ft', name:'Венгерский форинт', flag:'🇭🇺', rate:4.0, region:'europe' },
  { code:'SEK', sym:'kr', name:'Шведская крона', flag:'🇸🇪', rate:0.112, region:'europe' },
  { code:'NOK', sym:'kr', name:'Норвежская крона', flag:'🇳🇴', rate:0.118, region:'europe' },
  { code:'DKK', sym:'kr', name:'Датская крона', flag:'🇩🇰', rate:0.073, region:'europe' },
  { code:'RSD', sym:'дин.', name:'Сербский динар', flag:'🇷🇸', rate:1.15, region:'europe' },
  { code:'BGN', sym:'лв', name:'Болгарский лев', flag:'🇧🇬', rate:0.019, region:'europe' },
  { code:'RON', sym:'lei', name:'Румынский лей', flag:'🇷🇴', rate:0.049, region:'europe' },
  { code:'MDL', sym:'L', name:'Молдавский лей', flag:'🇲🇩', rate:0.19, region:'europe' },
  { code:'ISK', sym:'kr', name:'Исландская крона', flag:'🇮🇸', rate:1.52, region:'europe' },
  { code:'ALL', sym:'L', name:'Албанский лек', flag:'🇦🇱', rate:0.98, region:'europe' },
  { code:'BAM', sym:'KM', name:'Боснийская марка', flag:'🇧🇦', rate:0.019, region:'europe' },
  { code:'MKD', sym:'ден', name:'Македонский денар', flag:'🇲🇰', rate:0.60, region:'europe' },
  { code:'GIP', sym:'£', name:'Гибралтарский фунт', flag:'🇬🇮', rate:0.0084, region:'europe' },
  { code:'FKP', sym:'£', name:'Фунт Фолклендов', flag:'🇫🇰', rate:0.0084, region:'europe' },
  { code:'SHP', sym:'£', name:'Фунт Святой Елены', flag:'🇸🇭', rate:0.0084, region:'europe' },
  { code:'JEP', sym:'£', name:'Джерсийский фунт', flag:'🇯🇪', rate:0.0084, region:'europe' },
  { code:'GGP', sym:'£', name:'Гернсийский фунт', flag:'🇬🇬', rate:0.0084, region:'europe' },
  { code:'IMP', sym:'£', name:'Мэнский фунт', flag:'🇮🇲', rate:0.0084, region:'europe' },
  { code:'EUR_AD', sym:'€', name:'Андоррский евро', flag:'🇦🇩', rate:0.0098, region:'europe' },
  { code:'EUR_MC', sym:'€', name:'Монегасский евро', flag:'🇲🇨', rate:0.0098, region:'europe' },
  { code:'EUR_SM', sym:'€', name:'Сан-маринский евро', flag:'🇸🇲', rate:0.0098, region:'europe' },
  { code:'EUR_VA', sym:'€', name:'Ватиканский евро', flag:'🇻🇦', rate:0.0098, region:'europe' },
  { code:'EUR_ME', sym:'€', name:'Черногорский евро', flag:'🇲🇪', rate:0.0098, region:'europe' },
  { code:'EUR_XK', sym:'€', name:'Косовский евро', flag:'🇽🇰', rate:0.0098, region:'europe' },

  // --- AMERICAS (34) ---
  { code:'CAD', sym:'C$', name:'Канадский доллар', flag:'🇨🇦', rate:0.0148, region:'america' },
  { code:'BRL', sym:'R$', name:'Бразильский реал', flag:'🇧🇷', rate:0.062, region:'america' },
  { code:'MXN', sym:'Mex$', name:'Мексиканское песо', flag:'🇲🇽', rate:0.21, region:'america' },
  { code:'ARS', sym:'$', name:'Аргентинское песо', flag:'🇦🇷', rate:11.2, region:'america' },
  { code:'CLP', sym:'CLP$', name:'Чилийское песо', flag:'🇨🇱', rate:10.5, region:'america' },
  { code:'COP', sym:'COL$', name:'Колумбийское песо', flag:'🇨🇴', rate:45.0, region:'america' },
  { code:'PEN', sym:'S/.', name:'Перуанский соль', flag:'🇵🇪', rate:0.041, region:'america' },
  { code:'UYU', sym:'$U', name:'Уругвайское песо', flag:'🇺🇾', rate:0.43, region:'america' },
  { code:'BOB', sym:'Bs', name:'Боливийский боливиано', flag:'🇧🇴', rate:0.075, region:'america' },
  { code:'PYG', sym:'₲', name:'Парагвайский гуарани', flag:'🇵🇾', rate:82.0, region:'america' },
  { code:'CRC', sym:'₡', name:'Коста-риканский колон', flag:'🇨🇷', rate:5.5, region:'america' },
  { code:'DOP', sym:'RD$', name:'Доминиканское песо', flag:'🇩🇴', rate:0.65, region:'america' },
  { code:'GTQ', sym:'Q', name:'Гватемальский кетсаль', flag:'🇬🇹', rate:0.083, region:'america' },
  { code:'HNL', sym:'L', name:'Гондурасская лемпира', flag:'🇭🇳', rate:0.27, region:'america' },
  { code:'NIO', sym:'C$', name:'Никарагуанская кордоба', flag:'🇳🇮', rate:0.40, region:'america' },
  { code:'PAB', sym:'B/.', name:'Панамский бальбоа', flag:'🇵🇦', rate:0.0108, region:'america' },
  { code:'JMD', sym:'J$', name:'Ямайский доллар', flag:'🇯🇲', rate:1.68, region:'america' },
  { code:'TTD', sym:'TT$', name:'Доллар Тринидада', flag:'🇹🇹', rate:0.073, region:'america' },
  { code:'BSD', sym:'B$', name:'Багамский доллар', flag:'🇧🇸', rate:0.0108, region:'america' },
  { code:'BBD', sym:'Bds$', name:'Барбадосский доллар', flag:'🇧🇧', rate:0.0216, region:'america' },
  { code:'BZD', sym:'BZ$', name:'Белизский доллар', flag:'🇧🇿', rate:0.0216, region:'america' },
  { code:'BMD', sym:'BD$', name:'Бермудский доллар', flag:'🇧🇲', rate:0.0108, region:'america' },
  { code:'KYD', sym:'CI$', name:'Доллар Кайманов', flag:'🇰🇾', rate:0.009, region:'america' },
  { code:'XCD', sym:'EC$', name:'Восточно-карибский доллар', flag:'🇦🇮', rate:0.029, region:'america' },
  { code:'AWG', sym:'Afl.', name:'Арубанский флорин', flag:'🇦🇼', rate:0.0194, region:'america' },
  { code:'ANG', sym:'NAƒ', name:'Нидерландский антильский гульден', flag:'🇨🇼', rate:0.0194, region:'america' },
  { code:'HTG', sym:'G', name:'Гаитянский гурд', flag:'🇭🇹', rate:1.42, region:'america' },
  { code:'GYD', sym:'G$', name:'Гайанский доллар', flag:'🇬🇾', rate:2.25, region:'america' },
  { code:'SRD', sym:'Sr$', name:'Суринамский доллар', flag:'🇸🇷', rate:0.38, region:'america' },
  { code:'VES', sym:'Bs.', name:'Венесуэльский боливар', flag:'🇻🇪', rate:0.40, region:'america' },
  { code:'VED', sym:'Bs', name:'Боливар Соверен', flag:'🇻🇪', rate:0.40, region:'america' },
  { code:'CUP', sym:'₱', name:'Кубинское песо', flag:'🇨🇺', rate:0.26, region:'america' },
  { code:'SVC', sym:'₡', name:'Сальвадорский колон', flag:'🇸🇻', rate:0.094, region:'america' },

  // --- AFRICA (42) ---
  { code:'EGP', sym:'E£', name:'Египетский фунт', flag:'🇪🇬', rate:0.53, region:'africa' },
  { code:'ZAR', sym:'R', name:'Южноафриканский рэнд', flag:'🇿🇦', rate:0.198, region:'africa' },
  { code:'NGN', sym:'₦', name:'Нигерийская найра', flag:'🇳🇬', rate:17.5, region:'africa' },
  { code:'KES', sym:'KSh', name:'Кенийский шиллинг', flag:'🇰🇪', rate:1.40, region:'africa' },
  { code:'MAD', sym:'DH', name:'Марокканский дирхам', flag:'🇲🇦', rate:0.108, region:'africa' },
  { code:'DZD', sym:'DA', name:'Алжирский динар', flag:'🇩🇿', rate:1.45, region:'africa' },
  { code:'TND', sym:'DT', name:'Тунисский динар', flag:'🇹🇳', rate:0.033, region:'africa' },
  { code:'GHS', sym:'GH₵', name:'Ганский седи', flag:'🇬🇭', rate:0.165, region:'africa' },
  { code:'ETB', sym:'Br', name:'Эфиопский быр', flag:'🇪🇹', rate:1.35, region:'africa' },
  { code:'TZS', sym:'TSh', name:'Танзанийский шиллинг', flag:'🇹🇿', rate:28.5, region:'africa' },
  { code:'UGX', sym:'USh', name:'Угандийский шиллинг', flag:'🇺🇬', rate:40.0, region:'africa' },
  { code:'AOA', sym:'Kz', name:'Ангольская кванза', flag:'🇦🇴', rate:9.8, region:'africa' },
  { code:'BIF', sym:'FBu', name:'Бурундийский франк', flag:'🇧🇮', rate:31.0, region:'africa' },
  { code:'BWP', sym:'P', name:'Ботсванская пула', flag:'🇧🇼', rate:0.145, region:'africa' },
  { code:'CDF', sym:'FC', name:'Конголезский франк', flag:'🇨🇩', rate:30.5, region:'africa' },
  { code:'CVE', sym:'$', name:'Эскудо Кабо-Верде', flag:'🇨🇻', rate:1.08, region:'africa' },
  { code:'DJF', sym:'Fdj', name:'Франк Джибути', flag:'🇩🇯', rate:1.92, region:'africa' },
  { code:'ERN', sym:'Nfk', name:'Эритрейская накфа', flag:'🇪🇷', rate:0.162, region:'africa' },
  { code:'GMD', sym:'D', name:'Гамбийский даласи', flag:'🇬🇲', rate:0.74, region:'africa' },
  { code:'GNF', sym:'FG', name:'Гвинейский франк', flag:'🇬🇳', rate:93.0, region:'africa' },
  { code:'KMF', sym:'CF', name:'Коморский франк', flag:'🇰🇲', rate:4.85, region:'africa' },
  { code:'LRD', sym:'L$', name:'Либерийский доллар', flag:'🇱🇷', rate:2.1, region:'africa' },
  { code:'LSL', sym:'M', name:'Лесотский лоти', flag:'🇱🇸', rate:0.198, region:'africa' },
  { code:'LYD', sym:'LD', name:'Ливийский динар', flag:'🇱🇾', rate:0.052, region:'africa' },
  { code:'MGA', sym:'Ar', name:'Малагасийский ариари', flag:'🇲🇬', rate:49.5, region:'africa' },
  { code:'MRU', sym:'UM', name:'Мавританская угия', flag:'🇲🇷', rate:0.43, region:'africa' },
  { code:'MUR', sym:'₨', name:'Маврикийская рупия', flag:'🇲🇺', rate:0.50, region:'africa' },
  { code:'MWK', sym:'MK', name:'Малавийская квача', flag:'🇲🇼', rate:18.8, region:'africa' },
  { code:'MZN', sym:'MT', name:'Мозамбикский метикал', flag:'🇲🇿', rate:0.69, region:'africa' },
  { code:'NAD', sym:'N$', name:'Намибийский доллар', flag:'🇳🇦', rate:0.198, region:'africa' },
  { code:'RWF', sym:'FRw', name:'Руандийский франк', flag:'🇷🇼', rate:14.6, region:'africa' },
  { code:'SCR', sym:'SR', name:'Сейшельская рупия', flag:'🇸🇨', rate:0.15, region:'africa' },
  { code:'SDG', sym:'SDG', name:'Суданский фунт', flag:'🇸🇩', rate:6.5, region:'africa' },
  { code:'SLE', sym:'Le', name:'Сьерра-леонский леоне', flag:'🇸🇱', rate:0.24, region:'africa' },
  { code:'SOS', sym:'S', name:'Сомалийский шиллинг', flag:'🇸🇴', rate:6.15, region:'africa' },
  { code:'SSP', sym:'SS£', name:'Южносуданский фунт', flag:'🇸🇸', rate:14.0, region:'africa' },
  { code:'STN', sym:'Db', name:'Добра Сан-Томе', flag:'🇸🇹', rate:0.24, region:'africa' },
  { code:'SZL', sym:'E', name:'Свазилендский лилангени', flag:'🇸🇿', rate:0.198, region:'africa' },
  { code:'ZMW', sym:'ZK', name:'Замбийская квача', flag:'🇿🇲', rate:0.29, region:'africa' },
  { code:'ZWG', sym:'ZiG', name:'Зимбабвийский золотой', flag:'🇿🇼', rate:0.145, region:'africa' },
  { code:'XOF', sym:'CFA', name:'Франк КФА ВСЕАО', flag:'🇨🇮', rate:6.4, region:'africa' },
  { code:'XAF', sym:'FCFA', name:'Франк КФА БЭАС', flag:'🇨🇲', rate:6.4, region:'africa' },

  // --- OCEANIA (12) ---
  { code:'AUD', sym:'A$', name:'Австралийский доллар', flag:'🇦🇺', rate:0.0165, region:'oceania' },
  { code:'NZD', sym:'NZ$', name:'Новозеландский доллар', flag:'🇳🇿', rate:0.018, region:'oceania' },
  { code:'FJD', sym:'FJ$', name:'Доллар Фиджи', flag:'🇫🇯', rate:0.024, region:'oceania' },
  { code:'PGK', sym:'K', name:'Кина Папуа-Новой Гвинеи', flag:'🇵🇬', rate:0.043, region:'oceania' },
  { code:'SBD', sym:'SI$', name:'Доллар Соломоновых о-вов', flag:'🇸🇧', rate:0.091, region:'oceania' },
  { code:'TOP', sym:'T$', name:'Тонганская паанга', flag:'🇹🇴', rate:0.025, region:'oceania' },
  { code:'VUV', sym:'VT', name:'Вануатский вату', flag:'🇻🇺', rate:1.28, region:'oceania' },
  { code:'WST', sym:'WS$', name:'Самоанская тала', flag:'🇼🇸', rate:0.029, region:'oceania' },
  { code:'XPF', sym:'₣', name:'Французский тихоокеанский франк', flag:'🇵🇫', rate:1.18, region:'oceania' },
  { code:'KID', sym:'$', name:'Доллар Кирибати', flag:'🇰🇮', rate:0.0165, region:'oceania' },
  { code:'TVD', sym:'$', name:'Доллар Тувалу', flag:'🇹🇻', rate:0.0165, region:'oceania' },
  { code:'CKD', sym:'$', name:'Доллар Островов Кука', flag:'🇨🇰', rate:0.018, region:'oceania' },

  // --- METALS & IMF (5) ---
  { code:'XAU', sym:'XAU', name:'Золото (тройская унция)', flag:'🪙', rate:0.0000038, isApprox:true, region:'metals', type:'metal' },
  { code:'XAG', sym:'XAG', name:'Серебро (тройская унция)', flag:'🥈', rate:0.00032, isApprox:true, region:'metals', type:'metal' },
  { code:'XPT', sym:'XPT', name:'Платина (тройская унция)', flag:'⚪', rate:0.000011, isApprox:true, region:'metals', type:'metal' },
  { code:'XPD', sym:'XPD', name:'Палладий (тройская унция)', flag:'🔘', rate:0.000010, isApprox:true, region:'metals', type:'metal' },
  { code:'XDR', sym:'SDR', name:'СДР (МВФ)', flag:'🌐', rate:0.0081, isApprox:true, region:'metals', type:'imf' },

  // --- 60+ CRYPTOCURRENCIES (62) ---
  { code:'BTC', sym:'₿', name:'Bitcoin (BTC)', flag:'₿', rate:0.00000016, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'ETH', sym:'⟠', name:'Ethereum (ETH)', flag:'⟠', rate:0.0000041, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'USDT', sym:'₮', name:'Tether USD (USDT)', flag:'₮', rate:0.0108, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'USDC', sym:'USDC', name:'USD Coin (USDC)', flag:'💲', rate:0.0108, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'BNB', sym:'BNB', name:'BNB Chain (BNB)', flag:'🟡', rate:0.000018, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'SOL', sym:'SOL', name:'Solana (SOL)', flag:'🟣', rate:0.000072, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'XRP', sym:'XRP', name:'XRP (Ripple)', flag:'✕', rate:0.018, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'TON', sym:'TON', name:'Toncoin (TON)', flag:'💎', rate:0.0019, isApprox:true, region:'crypto', type:'crypto', popular:true },
  { code:'LTC', sym:'Ł', name:'Litecoin (LTC)', flag:'Ł', rate:0.00014, isApprox:true, region:'crypto', type:'crypto' },
  { code:'DOGE', sym:'Ð', name:'Dogecoin (DOGE)', flag:'🐕', rate:0.082, isApprox:true, region:'crypto', type:'crypto' },
  { code:'ADA', sym:'₳', name:'Cardano (ADA)', flag:'₳', rate:0.028, isApprox:true, region:'crypto', type:'crypto' },
  { code:'TRX', sym:'TRX', name:'TRON (TRX)', flag:'🔴', rate:0.065, isApprox:true, region:'crypto', type:'crypto' },
  { code:'AVAX', sym:'AVAX', name:'Avalanche (AVAX)', flag:'🔺', rate:0.00038, isApprox:true, region:'crypto', type:'crypto' },
  { code:'DOT', sym:'DOT', name:'Polkadot (DOT)', flag:'⚪', rate:0.0022, isApprox:true, region:'crypto', type:'crypto' },
  { code:'LINK', sym:'LINK', name:'Chainlink (LINK)', flag:'⬡', rate:0.00085, isApprox:true, region:'crypto', type:'crypto' },
  { code:'XLM', sym:'XLM', name:'Stellar (XLM)', flag:'🚀', rate:0.105, isApprox:true, region:'crypto', type:'crypto' },
  { code:'BCH', sym:'BCH', name:'Bitcoin Cash (BCH)', flag:'฿', rate:0.000028, isApprox:true, region:'crypto', type:'crypto' },
  { code:'ATOM', sym:'ATOM', name:'Cosmos (ATOM)', flag:'⚛️', rate:0.0021, isApprox:true, region:'crypto', type:'crypto' },
  { code:'NEAR', sym:'NEAR', name:'NEAR Protocol (NEAR)', flag:'🌐', rate:0.0024, isApprox:true, region:'crypto', type:'crypto' },
  { code:'POL', sym:'POL', name:'Polygon (POL / MATIC)', flag:'🟪', rate:0.024, isApprox:true, region:'crypto', type:'crypto' },
  { code:'SUI', sym:'SUI', name:'Sui Network (SUI)', flag:'💧', rate:0.0055, isApprox:true, region:'crypto', type:'crypto' },
  { code:'APT', sym:'APT', name:'Aptos (APT)', flag:'⚡', rate:0.0012, isApprox:true, region:'crypto', type:'crypto' },
  { code:'ARB', sym:'ARB', name:'Arbitrum (ARB)', flag:'🔷', rate:0.019, isApprox:true, region:'crypto', type:'crypto' },
  { code:'OP', sym:'OP', name:'Optimism (OP)', flag:'🔴', rate:0.0068, isApprox:true, region:'crypto', type:'crypto' },
  { code:'INJ', sym:'INJ', name:'Injective (INJ)', flag:'💉', rate:0.00045, isApprox:true, region:'crypto', type:'crypto' },
  { code:'KAS', sym:'KAS', name:'Kaspa (KAS)', flag:'🪙', rate:0.075, isApprox:true, region:'crypto', type:'crypto' },
  { code:'TIA', sym:'TIA', name:'Celestia (TIA)', flag:'🌌', rate:0.0018, isApprox:true, region:'crypto', type:'crypto' },
  { code:'RENDER', sym:'RENDER', name:'Render (RENDER)', flag:'🎨', rate:0.0016, isApprox:true, region:'crypto', type:'crypto' },
  { code:'FET', sym:'FET', name:'Artificial Superintelligence (FET)', flag:'🤖', rate:0.0075, isApprox:true, region:'crypto', type:'crypto' },
  { code:'PEPE', sym:'PEPE', name:'Pepe (PEPE)', flag:'🐸', rate:1150.0, isApprox:true, region:'crypto', type:'crypto' },
  { code:'SHIB', sym:'SHIB', name:'Shiba Inu (SHIB)', flag:'🐕', rate:580.0, isApprox:true, region:'crypto', type:'crypto' },
  { code:'FLOKI', sym:'FLOKI', name:'Floki (FLOKI)', flag:'⚔️', rate:65.0, isApprox:true, region:'crypto', type:'crypto' },
  { code:'BONK', sym:'BONK', name:'Bonk (BONK)', flag:'🐕', rate:450.0, isApprox:true, region:'crypto', type:'crypto' },
  { code:'WIF', sym:'WIF', name:'dogwifhat (WIF)', flag:'🎩', rate:0.0048, isApprox:true, region:'crypto', type:'crypto' },
  { code:'UNI', sym:'UNI', name:'Uniswap (UNI)', flag:'🦄', rate:0.0013, isApprox:true, region:'crypto', type:'crypto' },
  { code:'AAVE', sym:'AAVE', name:'Aave (AAVE)', flag:'👻', rate:0.00007, isApprox:true, region:'crypto', type:'crypto' },
  { code:'MKR', sym:'MKR', name:'Maker (MKR)', flag:'🏛️', rate:0.000006, isApprox:true, region:'crypto', type:'crypto' },
  { code:'ALGO', sym:'ALGO', name:'Algorand (ALGO)', flag:'🅰️', rate:0.075, isApprox:true, region:'crypto', type:'crypto' },
  { code:'ICP', sym:'ICP', name:'Internet Computer (ICP)', flag:'♾️', rate:0.0011, isApprox:true, region:'crypto', type:'crypto' },
  { code:'ETC', sym:'ETC', name:'Ethereum Classic (ETC)', flag:'🟢', rate:0.0005, isApprox:true, region:'crypto', type:'crypto' },
  { code:'FIL', sym:'FIL', name:'Filecoin (FIL)', flag:'📁', rate:0.0025, isApprox:true, region:'crypto', type:'crypto' },
  { code:'HBAR', sym:'HBAR', name:'Hedera (HBAR)', flag:'Ħ', rate:0.18, isApprox:true, region:'crypto', type:'crypto' },
  { code:'VET', sym:'VET', name:'VeChain (VET)', flag:'⚡', rate:0.42, isApprox:true, region:'crypto', type:'crypto' },
  { code:'GRT', sym:'GRT', name:'The Graph (GRT)', flag:'📊', rate:0.065, isApprox:true, region:'crypto', type:'crypto' },
  { code:'RUNE', sym:'RUNE', name:'THORChain (RUNE)', flag:'⚡', rate:0.0022, isApprox:true, region:'crypto', type:'crypto' },
  { code:'STX', sym:'STX', name:'Stacks (STX)', flag:'🧱', rate:0.006, isApprox:true, region:'crypto', type:'crypto' },
  { code:'TAO', sym:'TAO', name:'Bittensor (TAO)', flag:'🧠', rate:0.000022, isApprox:true, region:'crypto', type:'crypto' },
  { code:'SEI', sym:'SEI', name:'Sei Network (SEI)', flag:'🌊', rate:0.026, isApprox:true, region:'crypto', type:'crypto' },
  { code:'JUP', sym:'JUP', name:'Jupiter (JUP)', flag:'🪐', rate:0.012, isApprox:true, region:'crypto', type:'crypto' },
  { code:'PYTH', sym:'PYTH', name:'Pyth Network (PYTH)', flag:'🔮', rate:0.028, isApprox:true, region:'crypto', type:'crypto' },
  { code:'WLD', sym:'WLD', name:'Worldcoin (WLD)', flag:'👁️', rate:0.0055, isApprox:true, region:'crypto', type:'crypto' },
  { code:'FTM', sym:'FTM', name:'Fantom / Sonic (FTM)', flag:'👻', rate:0.015, isApprox:true, region:'crypto', type:'crypto' },
  { code:'EGLD', sym:'EGLD', name:'MultiversX (EGLD)', flag:'⚡', rate:0.00035, isApprox:true, region:'crypto', type:'crypto' },
  { code:'FLOW', sym:'FLOW', name:'Flow (FLOW)', flag:'🌊', rate:0.018, isApprox:true, region:'crypto', type:'crypto' },
  { code:'XTZ', sym:'XTZ', name:'Tezos (XTZ)', flag:'ꜩ', rate:0.013, isApprox:true, region:'crypto', type:'crypto' },
  { code:'EOS', sym:'EOS', name:'EOS (EOS)', flag:'mathcal{E}', rate:0.020, isApprox:true, region:'crypto', type:'crypto' },
  { code:'IOTA', sym:'IOTA', name:'IOTA (IOTA)', flag:'🌐', rate:0.065, isApprox:true, region:'crypto', type:'crypto' },
  { code:'KSM', sym:'KSM', name:'Kusama (KSM)', flag:'🦅', rate:0.00045, isApprox:true, region:'crypto', type:'crypto' },
  { code:'ZEC', sym:'ZEC', name:'Zcash (ZEC)', flag:'ⓩ', rate:0.00035, isApprox:true, region:'crypto', type:'crypto' },
  { code:'DASH', sym:'DASH', name:'Dash (DASH)', flag:'Đ', rate:0.00042, isApprox:true, region:'crypto', type:'crypto' },
  { code:'XMR', sym:'XMR', name:'Monero (XMR)', flag:'ɱ', rate:0.000072, isApprox:true, region:'crypto', type:'crypto' },
  { code:'TUSD', sym:'TUSD', name:'TrueUSD (TUSD)', flag:'₮', rate:0.0108, isApprox:true, region:'crypto', type:'crypto' },

  // --- HISTORICAL & OBSOLETE CURRENCIES (30) ---
  { code:'DEM', sym:'DM', name:'Немецкая марка (устаревшая)', flag:'🇩🇪', rate:0, isObsolete:true, region:'obsolete' },
  { code:'FRF', sym:'F', name:'Французский франк (устаревшая)', flag:'🇫🇷', rate:0, isObsolete:true, region:'obsolete' },
  { code:'ITL', sym:'L.', name:'Итальянская лира (устаревшая)', flag:'🇮🇹', rate:0, isObsolete:true, region:'obsolete' },
  { code:'ESP', sym:'₧', name:'Испанская песета (устаревшая)', flag:'🇪🇸', rate:0, isObsolete:true, region:'obsolete' },
  { code:'NLG', sym:'ƒ', name:'Нидерландский гульден (устаревшая)', flag:'🇳🇱', rate:0, isObsolete:true, region:'obsolete' },
  { code:'BEF', sym:'BF', name:'Бельгийский франк (устаревшая)', flag:'🇧🇪', rate:0, isObsolete:true, region:'obsolete' },
  { code:'ATS', sym:'S', name:'Австрийский шиллинг (устаревшая)', flag:'🇦🇹', rate:0, isObsolete:true, region:'obsolete' },
  { code:'PTE', sym:'$', name:'Португальское эскудо (устаревшая)', flag:'🇵🇹', rate:0, isObsolete:true, region:'obsolete' },
  { code:'FIM', sym:'mk', name:'Финляндская марка (устаревшая)', flag:'🇫🇮', rate:0, isObsolete:true, region:'obsolete' },
  { code:'GRD', sym:'₯', name:'Греческая драхма (устаревшая)', flag:'🇬🇷', rate:0, isObsolete:true, region:'obsolete' },
  { code:'IEP', sym:'£', name:'Ирландский фунт (устаревшая)', flag:'🇮🇪', rate:0, isObsolete:true, region:'obsolete' },
  { code:'LUF', sym:'F', name:'Люксембургский франк (устаревшая)', flag:'🇱🇺', rate:0, isObsolete:true, region:'obsolete' },
  { code:'CYP', sym:'£', name:'Кипрский фунт (устаревшая)', flag:'🇨🇾', rate:0, isObsolete:true, region:'obsolete' },
  { code:'MTL', sym:'Lm', name:'Мальтийская лира (устаревшая)', flag:'🇲🇹', rate:0, isObsolete:true, region:'obsolete' },
  { code:'SIT', sym:'SIT', name:'Словенский толар (устаревшая)', flag:'🇸🇮', rate:0, isObsolete:true, region:'obsolete' },
  { code:'SKK', sym:'Sk', name:'Словацкая крона (устаревшая)', flag:'🇸🇰', rate:0, isObsolete:true, region:'obsolete' },
  { code:'EEK', sym:'kr', name:'Эстонская крона (устаревшая)', flag:'🇪🇪', rate:0, isObsolete:true, region:'obsolete' },
  { code:'LVL', sym:'Ls', name:'Латвийский лат (устаревшая)', flag:'🇱🇻', rate:0, isObsolete:true, region:'obsolete' },
  { code:'LTL', sym:'Lt', name:'Литовский лит (устаревшая)', flag:'🇱🇹', rate:0, isObsolete:true, region:'obsolete' },
  { code:'SUR', sym:'руб.', name:'Советский рубль (СССР)', flag:'🚩', rate:0, isObsolete:true, region:'obsolete' },
  { code:'CSK', sym:'Kčs', name:'Чехословацкая крона', flag:'🇨🇿', rate:0, isObsolete:true, region:'obsolete' },
  { code:'YUD', sym:'дин.', name:'Югославский динар', flag:'🇷🇸', rate:0, isObsolete:true, region:'obsolete' },
  { code:'HRK_OLD', sym:'kn', name:'Хорватская куна (до 2023)', flag:'🇭🇷', rate:0, isObsolete:true, region:'obsolete' },
  { code:'TRL', sym:'TL', name:'Старая турецкая лира', flag:'🇹🇷', rate:0, isObsolete:true, region:'obsolete' },
  { code:'ZWD', sym:'Z$', name:'Старый зимбабвийский доллар', flag:'🇿🇼', rate:0, isObsolete:true, region:'obsolete' },
  { code:'VEF', sym:'Bs.F', name:'Боливар Фуэрте', flag:'🇻🇪', rate:0, isObsolete:true, region:'obsolete' },
  { code:'BYR', sym:'Br', name:'Старый белорусский рубль', flag:'🇧🇾', rate:0, isObsolete:true, region:'obsolete' },
  { code:'TMM', sym:'m', name:'Старый туркменский манат', flag:'🇹🇲', rate:0, isObsolete:true, region:'obsolete' },
  { code:'AZM', sym:'ман.', name:'Старый азербайджанский манат', flag:'🇦🇿', rate:0, isObsolete:true, region:'obsolete' },
  { code:'SDD', sym:'LSd', name:'Старый суданский динар', flag:'🇸🇩', rate:0, isObsolete:true, region:'obsolete' }
];

export const REGIONS_META = [
  { id: 'all', name: 'Все (256+)' },
  { id: 'popular', name: '⚡ Популярные' },
  { id: 'favorites', name: '⭐ Избранные' },
  { id: 'crypto', name: '🪙 Криптовалюты (60+)' },
  { id: 'metals', name: '🏆 Металлы & МВФ' },
  { id: 'asia', name: '🌏 Азия & СНГ' },
  { id: 'europe', name: '🌍 Европа' },
  { id: 'america', name: '🌎 Америка' },
  { id: 'africa', name: '🌍 Африка' },
  { id: 'oceania', name: '🏝️ Океания' },
  { id: 'obsolete', name: '⏳ Устаревшие (30)' }
];
